### PR TITLE
refactor: split of publish workflow

### PR DESCRIPTION
**Pull request by k3rnelpan1c-dev**
### Description

This PR picks up the idea from the backend CI and aims to fix the incorrect version reported by the releases originated from the current CI.

### Changes

* splits off publish build to a separate workflow

### Issues

* address the comment from the previous CI PR https://github.com/DependencyTrack/frontend/pull/141#issuecomment-1130326345

### CODE REVIEW

**Comment by nscuro** [comment]
Thanks for yet another great PR, @k3rnelpan1c-dev! Can we adopt the release branch handling from the API server workflows as well? There are some features scheduled for 4.6, but we may need to push out another 4.5.x release in the meantime.

**Comment by k3rnelpan1c-dev** [comment]
So you want to have release branches for the frontend repo?
I sure can port the handling over, will try and do that over the weekend maybe :thinking:

**Comment by nscuro** [comment]
That'd be awesome. I'm going to merge this PR now though, as supporting release branches would be a separate feature I guess. 😅

**Comment by k3rnelpan1c-dev** [comment]
> That'd be awesome. I'm going to merge this PR now though, as supporting release branches would be a separate feature I guess. sweat_smile

Sounds good to me :)

On a different note: saw that there will be a BOT user soon :+1: Just my 2 cents, but I recommend configuring that secret with its PAT on the org level and granting access to it on a repo per repo basis => only one place to maintain it :wink:

**Pull request merged**
