### PR TITLE
feat(components): quick search for projects also using component 

### PR DESCRIPTION
**Pull request by setchy**
### Description

Ability to quickly launch a component PURL search from within a component details screen.

Allows to easily find similar projects using the same library.

Open to suggestions on a better name for this quick-launch tab. 

### Additional Details

Screenshot 2024-01-31 at 6 33 34 PM

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#pull-requests)
- [x] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by setchy** [comment]
addressed the merge conflict

**Comment by setchy** [comment]
@nscuro - thoughts on this enhancement?

**Comment by setchy** [comment]
@nscuro - for the failed i18n step - do I need to add a translation for my new key into the other language files?  is there a documented process for fetching these?

**Comment by nscuro** [comment]
@setchy Yes, please have a look here: https://github.com/DependencyTrack/frontend?tab=readme-ov-file#adding-or-improving-translations

**Comment by setchy** [comment]
Awesome - that was super simple!

**Comment by setchy** [comment]
DCO Hell - re-raising: https://github.com/DependencyTrack/frontend/pull/848

**Pull request closed without merging**
