### PR TITLE
add support from localization based on browser and languages

### PR DESCRIPTION
**Pull request by fnxpt**
### Description

- Add support for i18n based on browser
- Sorted EN file
- Added missing strings to EN file
- Removed unused strings from EN file
- Removed md5/sha strings from messages and moved them to hashes
- Added auto translation for de
- Added auto translation for es
- Added auto translation for fr
- Added auto translation for hi
- Added auto translation for it
- Added auto translation for ja
- Added auto translation for pl
- Added auto translation for pt
- Added auto translation for pt-BR
- Added auto translation for ru
- Added auto translation for zh

strings added missing:
```
│          'admin.team_created'           │ './src/views/administration/accessmanagement/CreateTeamModal.vue' │  57  │
│       'admin.oidc_group_deleted'        │   './src/views/administration/accessmanagement/OidcGroups.vue'    │ 152  │
│         'condition.successful'          │    './src/views/administration/mixins/configPropertyMixin.js'     │  49  │
│             'message.purl'              │   './src/views/portfolio/projects/ProjectPolicyViolations.vue'    │ 214  │
│             'message.swid'              │   './src/views/portfolio/projects/ProjectPolicyViolations.vue'    │ 220  │
```

strings removed unused:
```
admin.enable_bom_spdx
admin.template_cloned
admin.threadfix
condition.http_status_code
condition.warning
message.add_service
message.affects
message.alias
message.audit
message.component_added
message.component_group
message.component_removed
message.component_version
message.cwe_desc
message.dependencies
message.download
message.remove_service
message.subject
message.used_by
message.vex_long_desc
message.vulnerability_source
message.vulnerability_source_desc
message.vulnerability_subtitle
message.vulnerability_subtitle_desc
message.vulnerable_dependencies
```

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#pull-requests)
- [x] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by fnxpt** [comment]
Im not sure if these strings are being used

**Comment by nscuro** [comment]
> Im not sure if these strings are being used

It does indeed look like those are unused and safe to remove :+1: 

@fnxpt Is it possible to add instructions on what you did for the auto-translation part? Thinking in terms of contributors here. If they add new fields and CI starts failing due to incomplete translations, we'll need instructions on what to do to resolve.

Separately, I know you said the language can be switched in the browser. Would there be any point in adding an application-level toggle as well? Say my browser is set to German, but I actually prefer to use my applications in english.

**Comment by fnxpt** [comment]
The language is set by the browser configuration, we are setting the first language defined on the browser, in order to change the language we just need to change the order and put the language we want as the primary language.
Screenshot 2024-04-10 at 16 58 38

Regading the auto-translation was a mixed of manual/automatic work... initially I did all automatically using cloud translation api (which is paid but I had a few credits) but I realised that some of the translations were not correct, so I swich to googles translation page (a little bit more manual but I kind of found a way to make it simple, and didn't really want to waste time looking for a solution that would only be used once or twice)

**Comment by fnxpt** [comment]
ok, I had a better look on how we can improve the automation part, the plugin I suggested for vscode supports this
https://github.com/lokalise/i18n-ally/wiki/Machine-Translation

**Comment by fnxpt** [comment]
On vscode when edditing a translation there ia a translate all button or a translate button per language

**Review by nscuro — APPROVED** [review]
Thanks @fnxpt, great enhancement!

**Comment by setchy** [comment]
@fnxpt - nice addition.

We might need to update [this section](https://github.com/DependencyTrack/frontend?tab=readme-ov-file#internationalization-i18n) in the projects README.md 😄

**Pull request merged**
