### PR TITLE
feat(component): add internal / external classification badge

### PR DESCRIPTION
**Pull request by setchy**
### Description

Add an `internal` or `external` badge to the component view and component details model.

I'd appreciate feedback/input on the correct terminology to use for this.  I went with _component_source_ for this PR, but was also contemplating _component_scope_

### Addressed Issue

Previously, there was no way through the UI to determine if a component was `internal` or `external`

### Additional Details

Screenshot 2024-03-13 at 6 36 49 AM
Screenshot 2024-03-13 at 6 36 58 AM

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#pull-requests)
- [x] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by setchy** [comment]
@nscuro - do you happen to have any feedback on this enhancement suggestion?

**Comment by nscuro** [comment]
@setchy Thanks for the ping! I like the idea of having this badge. But I am also not super sure about the label name. :thinking: 

We need to be cautious to not use terms that could be confused with [provenance](https://cyclonedx.org/use-cases/#provenance), which I think would be the case for *component source*. Similar story for *component origin* for example.

> [...] but was also contemplating *component_scope*

Scope might be confused with [`component.scope`](https://cyclonedx.org/docs/1.5/json/#components_items_scope) in the spec, which to be fair, DT currently does not display.

How about *classification*? Similar to how a business would *classify* documents as confidential or not. In our case, components would be classified as either internal or external.

**Comment by setchy** [comment]
Exactly the type of feedback I needed!  Really like the suggestion to use `Classification`.  Will update asap

**Comment by setchy** [comment]
Updated terminology to use `Classification`

**Review by nscuro — APPROVED** [review]
Thanks!

**Pull request merged**
