### PR TITLE
feat: add eslint and prettier

### PR DESCRIPTION
**Pull request by setchy**
### Description

Add eslint and prettier to help enforce consistent coding practices and formating

### Additional Details

Based on feedback, I can commit the formatting changes within this PR, or a separate PR (assuming this is approved/merged).   

There are 161 files with formatting updates, and 633 errors detected by eslint

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#pull-requests)
- [x] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by nscuro** [comment]
Great idea!

> Based on feedback, I can commit the formatting changes within this PR, or a separate PR (assuming this is approved/merged).

I am OK with doing it in this PR.

N00b question: Is there a possibility to fail the build when files are not properly formatted?

**Comment by setchy** [comment]
> I am OK with doing it in this PR.

Perfect. I'll push the formatting updates to this PR in the morning.

> N00b question: Is there a possibility to fail the build when files are not properly formatted?

Absolutely. I'll add a GitHub Action workflow to validate the formatting. Linting will need to come much later if/when the hundreds of errors are resolved.

**Comment by setchy** [comment]
@nscuro @msymons - I have added a GitHub workflow, which for now i've set to continue-on-error.

Some stats before running the automated linting fixes

> ES-Lint: 15380 problems (15380 errors, 0 warnings)
> Prettier: Code style issues in 175 files

After running prettier for code formatting

> 640 problems (640 errors, 0 warnings)

**Comment by nscuro** [comment]
@setchy With the Codacy issue resolved, do you feel this is now ready for review?

**Comment by setchy** [comment]
@nscuro - READY!

**Review by nscuro — APPROVED** [review]
Thanks so much for this! 🙌

**Pull request merged**
